CC=g++

all: kmeansClusteringGroupPointrsDataset

kmeansClusteringGroupPointrsDataset: kmeansClusteringGroupPointrsDataset.cpp
	$(CC) kmeansClusteringGroupPointrsDataset.cpp -o kmeansClusteringGroupPointrsDataset

run: kmeansClusteringGroupPointrsDataset
	./kmeansClusteringGroupPointrsDataset

clean:
	#rm -f kmeansClusteringGroupPointrsDataset
	rm -f *o
